# Generated by Django 2.0.6 on 2018-08-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecomponent',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
