# Generated by Django 2.0.6 on 2018-08-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario_stats', '0002_long_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='outcome',
            field=models.IntegerField(choices=[(1, 'won'), (2, 'lost'), (3, 'draw'), (4, 'not played')], default=4),
        ),
        migrations.AlterField(
            model_name='person',
            name='handicap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
