# Generated by Django 2.0.6 on 2018-08-05 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mario_stats', '0003_default_handicap_and_game_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handicapsnapshot',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handicap_snapshot', to='mario_stats.Game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='mario_stats.Game'),
        ),
        migrations.AlterField(
            model_name='playerhandicapsnapshot',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='mario_stats.HandicapSnapshot'),
        ),
    ]
